// Autogenerated using cbuild
System.config({
	map: {
		"./CRS": "packages/node_modules/charto-leaflet/dist/CRS.js",
		"./CanvasLayer": "packages/node_modules/charto-leaflet/dist/CanvasLayer.js",
		"./CanvasRenderer": "packages/node_modules/charto-render/dist/CanvasRenderer.js",
		"./CircularString": "node_modules/cgeo-cpak/node_modules/cgeo/dist/CircularString.js",
		"./CompoundCurve": "node_modules/cgeo-cpak/node_modules/cgeo/dist/CompoundCurve.js",
		"./Curve": "node_modules/cgeo-cpak/node_modules/cgeo/dist/Curve.js",
		"./CurvePolygon": "node_modules/cgeo-cpak/node_modules/cgeo/dist/CurvePolygon.js",
		"./Dialog": "node_modules/phosphor-float-area/dist/Dialog.js",
		"./DialogLayout": "node_modules/phosphor-float-area/dist/DialogLayout.js",
		"./DialogMessage": "node_modules/phosphor-float-area/dist/DialogMessage.js",
		"./Feature": "packages/node_modules/charto-model/dist/Feature.js",
		"./FloatArea": "node_modules/phosphor-float-area/dist/FloatArea.js",
		"./FloatLayout": "node_modules/phosphor-float-area/dist/FloatLayout.js",
		"./GeoTile": "packages/node_modules/geotree/dist/GeoTile.js",
		"./GeoTree": "packages/node_modules/geotree/dist/GeoTree.js",
		"./Geometry": "node_modules/cgeo-cpak/node_modules/cgeo/dist/Geometry.js",
		"./GeometryCollection": "node_modules/cgeo-cpak/node_modules/cgeo/dist/GeometryCollection.js",
		"./Layer": "packages/node_modules/charto-model/dist/Layer.js",
		"./LeafletMap": "packages/node_modules/phosphor-leaflet/dist/LeafletMap.js",
		"./LineString": "node_modules/cgeo-cpak/node_modules/cgeo/dist/LineString.js",
		"./MapModel": "packages/node_modules/charto-model/dist/MapModel.js",
		"./Mstore": "packages/node_modules/mst-dstore/dist/Mstore.js",
		"./MultiCurve": "node_modules/cgeo-cpak/node_modules/cgeo/dist/MultiCurve.js",
		"./MultiLineString": "node_modules/cgeo-cpak/node_modules/cgeo/dist/MultiLineString.js",
		"./MultiPoint": "node_modules/cgeo-cpak/node_modules/cgeo/dist/MultiPoint.js",
		"./MultiPolygon": "node_modules/cgeo-cpak/node_modules/cgeo/dist/MultiPolygon.js",
		"./MultiSurface": "node_modules/cgeo-cpak/node_modules/cgeo/dist/MultiSurface.js",
		"./Point": "node_modules/cgeo-cpak/node_modules/cgeo/dist/Point.js",
		"./Polygon": "node_modules/cgeo-cpak/node_modules/cgeo/dist/Polygon.js",
		"./Projection": "packages/node_modules/charto-leaflet/dist/Projection.js",
		"./QuadTile": "packages/node_modules/geotree/dist/QuadTile.js",
		"./QuadTree": "packages/node_modules/geotree/dist/QuadTree.js",
		"./RExp": "packages/node_modules/charto-model/dist/frozen/RExp.js",
		"./Reader": "node_modules/cgeo-cpak/node_modules/cpak/dist/Reader.js",
		"./SimpleLayout": "node_modules/phosphor-float-area/dist/SimpleLayout.js",
		"./Surface": "node_modules/cgeo-cpak/node_modules/cgeo/dist/Surface.js",
		"./Writer": "node_modules/cgeo-cpak/node_modules/cpak/dist/Writer.js",
		"./array": "node_modules/@phosphor/algorithm/lib/array.js",
		"./bindModel": "packages/node_modules/charto-leaflet/dist/bindModel.js",
		"./boxengine": "node_modules/@phosphor/widgets/lib/boxengine.js",
		"./boxlayout": "node_modules/@phosphor/widgets/lib/boxlayout.js",
		"./boxpanel": "node_modules/@phosphor/widgets/lib/boxpanel.js",
		"./chain": "node_modules/@phosphor/algorithm/lib/chain.js",
		"./classy-mst": "node_modules/classy-mst/dist/classy-mst.js",
		"./commandpalette": "node_modules/@phosphor/widgets/lib/commandpalette.js",
		"./contextmenu": "node_modules/@phosphor/widgets/lib/contextmenu.js",
		"./docklayout": "node_modules/@phosphor/widgets/lib/docklayout.js",
		"./dockpanel": "node_modules/@phosphor/widgets/lib/dockpanel.js",
		"./element": "node_modules/@phosphor/domutils/lib/element.js",
		"./empty": "node_modules/@phosphor/algorithm/lib/empty.js",
		"./filter": "node_modules/@phosphor/algorithm/lib/filter.js",
		"./find": "node_modules/@phosphor/algorithm/lib/find.js",
		"./focustracker": "node_modules/@phosphor/widgets/lib/focustracker.js",
		"./frozen/BBox": "packages/node_modules/charto-model/dist/frozen/BBox.js",
		"./frozen/SRS": "packages/node_modules/charto-model/dist/frozen/SRS.js",
		"./gridlayout": "node_modules/@phosphor/widgets/lib/gridlayout.js",
		"./iter": "node_modules/@phosphor/algorithm/lib/iter.js",
		"./json": "node_modules/@phosphor/coreutils/lib/json.js",
		"./layout": "node_modules/@phosphor/widgets/lib/layout.js",
		"./linkedlist": "node_modules/@phosphor/collections/lib/linkedlist.js",
		"./map": "node_modules/@phosphor/algorithm/lib/map.js",
		"./menu": "node_modules/@phosphor/widgets/lib/menu.js",
		"./menubar": "node_modules/@phosphor/widgets/lib/menubar.js",
		"./mime": "node_modules/@phosphor/coreutils/lib/mime.js",
		"./panel": "node_modules/@phosphor/widgets/lib/panel.js",
		"./panellayout": "node_modules/@phosphor/widgets/lib/panellayout.js",
		"./platform": "node_modules/@phosphor/domutils/lib/platform.js",
		"./promise": "node_modules/@phosphor/coreutils/lib/promise.js",
		"./random": "node_modules/@phosphor/coreutils/lib/random.js",
		"./range": "node_modules/@phosphor/algorithm/lib/range.js",
		"./reduce": "node_modules/@phosphor/algorithm/lib/reduce.js",
		"./repeat": "node_modules/@phosphor/algorithm/lib/repeat.js",
		"./retro": "node_modules/@phosphor/algorithm/lib/retro.js",
		"./scrollbar": "node_modules/@phosphor/widgets/lib/scrollbar.js",
		"./selector": "node_modules/@phosphor/domutils/lib/selector.js",
		"./sort": "node_modules/@phosphor/algorithm/lib/sort.js",
		"./splitlayout": "node_modules/@phosphor/widgets/lib/splitlayout.js",
		"./splitpanel": "node_modules/@phosphor/widgets/lib/splitpanel.js",
		"./stackedlayout": "node_modules/@phosphor/widgets/lib/stackedlayout.js",
		"./stackedpanel": "node_modules/@phosphor/widgets/lib/stackedpanel.js",
		"./stride": "node_modules/@phosphor/algorithm/lib/stride.js",
		"./string": "node_modules/@phosphor/algorithm/lib/string.js",
		"./tabbar": "node_modules/@phosphor/widgets/lib/tabbar.js",
		"./tabpanel": "node_modules/@phosphor/widgets/lib/tabpanel.js",
		"./take": "node_modules/@phosphor/algorithm/lib/take.js",
		"./title": "node_modules/@phosphor/widgets/lib/title.js",
		"./token": "node_modules/@phosphor/coreutils/lib/token.js",
		"./uuid": "node_modules/@phosphor/coreutils/lib/uuid.js",
		"./widget": "node_modules/@phosphor/widgets/lib/widget.js",
		"./zip": "node_modules/@phosphor/algorithm/lib/zip.js",
		"@phosphor/algorithm": "node_modules/@phosphor/algorithm",
		"@phosphor/collections": "node_modules/@phosphor/collections",
		"@phosphor/commands": "node_modules/@phosphor/commands",
		"@phosphor/coreutils": "node_modules/@phosphor/coreutils",
		"@phosphor/disposable": "node_modules/@phosphor/disposable",
		"@phosphor/domutils": "node_modules/@phosphor/domutils",
		"@phosphor/dragdrop": "node_modules/@phosphor/dragdrop",
		"@phosphor/dragdrop/style/index.css": "node_modules/@phosphor/dragdrop/style/index.css",
		"@phosphor/keyboard": "node_modules/@phosphor/keyboard",
		"@phosphor/messaging": "node_modules/@phosphor/messaging",
		"@phosphor/properties": "node_modules/@phosphor/properties",
		"@phosphor/signaling": "node_modules/@phosphor/signaling",
		"@phosphor/virtualdom": "node_modules/@phosphor/virtualdom",
		"@phosphor/widgets": "node_modules/@phosphor/widgets",
		"@phosphor/widgets/style/index.css": "node_modules/@phosphor/widgets/style/index.css",
		"cgeo": "node_modules/cgeo",
		"cgeo-cpak": "node_modules/cgeo-cpak",
		"charto-ajax": "node_modules/charto-ajax",
		"charto-leaflet": "packages/node_modules/charto-leaflet",
		"charto-model": "packages/node_modules/charto-model",
		"charto-render": "packages/node_modules/charto-render",
		"classy-mst": "node_modules/classy-mst",
		"cpak": "node_modules/cgeo-cpak/node_modules/cpak",
		"dgrid/Editor": "node_modules/dgrid/Editor.js",
		"dgrid/Keyboard": "node_modules/dgrid/Keyboard.js",
		"dgrid/OnDemandGrid": "node_modules/dgrid/OnDemandGrid.js",
		"dgrid/Selection": "node_modules/dgrid/Selection.js",
		"dgrid/Tree": "node_modules/dgrid/Tree.js",
		"dgrid/extensions/ColumnResizer": "node_modules/dgrid/extensions/ColumnResizer.js",
		"dgrid/extensions/DnD": "node_modules/dgrid/extensions/DnD.js",
		"dojo/Deferred": "node_modules/dojo/Deferred.js",
		"dojo/Evented": "node_modules/dojo/Evented.js",
		"dojo/_base/NodeList": "node_modules/dojo/_base/NodeList.js",
		"dojo/_base/array": "node_modules/dojo/_base/array.js",
		"dojo/_base/declare": "node_modules/dojo/_base/declare.js",
		"dojo/_base/html": "node_modules/dojo/_base/html.js",
		"dojo/_base/lang": "node_modules/dojo/_base/lang.js",
		"dojo/_base/sniff": "node_modules/dojo/_base/sniff.js",
		"dojo/aspect": "node_modules/dojo/aspect.js",
		"dojo/dnd/Manager": "node_modules/dojo/dnd/Manager.js",
		"dojo/dnd/Source": "node_modules/dojo/dnd/Source.js",
		"dojo/dom": "node_modules/dojo/dom.js",
		"dojo/dom-class": "node_modules/dojo/dom-class.js",
		"dojo/dom-construct": "node_modules/dojo/dom-construct.js",
		"dojo/dom-geometry": "node_modules/dojo/dom-geometry.js",
		"dojo/has": "node_modules/dojo/has.js",
		"dojo/on": "node_modules/dojo/on.js",
		"dojo/promise/all": "node_modules/dojo/promise/all.js",
		"dojo/query": "node_modules/dojo/query.js",
		"dojo/resources/dnd.css": "node_modules/dojo/resources/dnd.css",
		"dojo/topic": "node_modules/dojo/topic.js",
		"dojo/when": "node_modules/dojo/when.js",
		"font-awesome/css/font-awesome.min.css": "node_modules/font-awesome/css/font-awesome.min.css",
		"geotree": "packages/node_modules/geotree",
		"leaflet": "node_modules/leaflet",
		"leaflet/dist/leaflet.css": "node_modules/leaflet/dist/leaflet.css",
		"mobx": "node_modules/mobx",
		"mobx-state-tree": "node_modules/mobx-state-tree",
		"mst-dstore": "packages/node_modules/mst-dstore",
		"phosphor-float-area": "node_modules/phosphor-float-area",
		"phosphor-float-area/style/index.css": "node_modules/phosphor-float-area/style/index.css",
		"phosphor-leaflet": "packages/node_modules/phosphor-leaflet"
	},
	meta: {
		"node_modules/*": { globals: { process: "bundler/node_modules/cbuild/process-dev.js" } },
		"packages/node_modules/*": { globals: { process: "bundler/node_modules/cbuild/process-dev.js" } }
	},
	packages: {
		"@phosphor/algorithm": {
			main: "lib/index.js"
		},
		"@phosphor/collections": {
			main: "lib/index.js"
		},
		"@phosphor/commands": {
			main: "lib/index.js"
		},
		"@phosphor/coreutils": {
			main: "lib/index.js"
		},
		"@phosphor/disposable": {
			main: "lib/index.js"
		},
		"@phosphor/domutils": {
			main: "lib/index.js"
		},
		"@phosphor/dragdrop": {
			main: "lib/index.js"
		},
		"@phosphor/keyboard": {
			main: "lib/index.js"
		},
		"@phosphor/messaging": {
			main: "lib/index.js"
		},
		"@phosphor/properties": {
			main: "lib/index.js"
		},
		"@phosphor/signaling": {
			main: "lib/index.js"
		},
		"@phosphor/virtualdom": {
			main: "lib/index.js"
		},
		"@phosphor/widgets": {
			main: "lib/index.js"
		},
		"cgeo": {
			main: "dist/index.js"
		},
		"cgeo-cpak": {
			main: "dist/index.js"
		},
		"charto-ajax": {
			main: "dist/index.js"
		},
		"charto-leaflet": {
			main: "dist/index.js"
		},
		"charto-model": {
			main: "dist/index.js"
		},
		"charto-render": {
			main: "dist/index.js"
		},
		"classy-mst": {
			main: "dist/index.js"
		},
		"cpak": {
			main: "dist/index.js"
		},
		"geotree": {
			main: "dist/index.js"
		},
		"leaflet": {
			main: "dist/leaflet-src.js"
		},
		"mobx": {
			main: "lib/mobx.js"
		},
		"mobx-state-tree": {
			main: "dist/mobx-state-tree.js"
		},
		"mst-dstore": {
			main: "dist/index.js"
		},
		"phosphor-float-area": {
			main: "dist/index.js"
		},
		"phosphor-leaflet": {
			main: "dist/index.js"
		}
	}
});
