// Autogenerated using cbuild
System.config({
	map: {
		"@phosphor/algorithm": "node_modules/@phosphor/algorithm",
		"@phosphor/collections": "node_modules/@phosphor/collections",
		"@phosphor/commands": "node_modules/@phosphor/commands",
		"@phosphor/coreutils": "node_modules/@phosphor/coreutils",
		"@phosphor/disposable": "node_modules/@phosphor/disposable",
		"@phosphor/domutils": "node_modules/@phosphor/domutils",
		"@phosphor/dragdrop": "node_modules/@phosphor/dragdrop",
		"@phosphor/dragdrop/style/index.css": "node_modules/@phosphor/dragdrop/style/index.css",
		"@phosphor/keyboard": "node_modules/@phosphor/keyboard",
		"@phosphor/messaging": "node_modules/@phosphor/messaging",
		"@phosphor/properties": "node_modules/@phosphor/properties",
		"@phosphor/signaling": "node_modules/@phosphor/signaling",
		"@phosphor/virtualdom": "node_modules/@phosphor/virtualdom",
		"@phosphor/widgets": "node_modules/@phosphor/widgets",
		"@phosphor/widgets/style/index.css": "node_modules/@phosphor/widgets/style/index.css",
		"charto-leaflet": "packages/node_modules/charto-leaflet",
		"charto-model": "packages/node_modules/charto-model",
		"classy-mst": "node_modules/classy-mst",
		"fbjs/lib/EventListener": "node_modules/fbjs/lib/EventListener.js",
		"fbjs/lib/ExecutionEnvironment": "node_modules/fbjs/lib/ExecutionEnvironment.js",
		"fbjs/lib/camelizeStyleName": "node_modules/fbjs/lib/camelizeStyleName.js",
		"fbjs/lib/containsNode": "node_modules/fbjs/lib/containsNode.js",
		"fbjs/lib/emptyFunction": "node_modules/fbjs/lib/emptyFunction.js",
		"fbjs/lib/emptyObject": "node_modules/fbjs/lib/emptyObject.js",
		"fbjs/lib/focusNode": "node_modules/fbjs/lib/focusNode.js",
		"fbjs/lib/getActiveElement": "node_modules/fbjs/lib/getActiveElement.js",
		"fbjs/lib/hyphenateStyleName": "node_modules/fbjs/lib/hyphenateStyleName.js",
		"fbjs/lib/invariant": "node_modules/fbjs/lib/invariant.js",
		"fbjs/lib/shallowEqual": "node_modules/fbjs/lib/shallowEqual.js",
		"fbjs/lib/warning": "node_modules/fbjs/lib/warning.js",
		"leaflet": "node_modules/leaflet",
		"leaflet/dist/leaflet.css": "node_modules/leaflet/dist/leaflet.css",
		"mobx": "node_modules/mobx",
		"mobx-state-tree": "node_modules/mobx-state-tree",
		"object-assign": "node_modules/object-assign",
		"phosphor-float-area": "node_modules/phosphor-float-area",
		"phosphor-float-area/style/index.css": "node_modules/phosphor-float-area/style/index.css",
		"phosphor-leaflet": "packages/node_modules/phosphor-leaflet",
		"prop-types/checkPropTypes": "node_modules/prop-types/checkPropTypes.js",
		"react": "node_modules/react",
		"react-dom": "node_modules/react-dom"
	},
	meta: {
		"node_modules/*": { globals: { process: "bundler/node_modules/cbuild/process-dev.js" } },
		"packages/node_modules/*": { globals: { process: "bundler/node_modules/cbuild/process-dev.js" } }
	},
	packages: {
		"@phosphor/algorithm": {
			main: "lib/index.js"
		},
		"@phosphor/collections": {
			main: "lib/index.js"
		},
		"@phosphor/commands": {
			main: "lib/index.js"
		},
		"@phosphor/coreutils": {
			main: "lib/index.js"
		},
		"@phosphor/disposable": {
			main: "lib/index.js"
		},
		"@phosphor/domutils": {
			main: "lib/index.js"
		},
		"@phosphor/dragdrop": {
			main: "lib/index.js"
		},
		"@phosphor/keyboard": {
			main: "lib/index.js"
		},
		"@phosphor/messaging": {
			main: "lib/index.js"
		},
		"@phosphor/properties": {
			main: "lib/index.js"
		},
		"@phosphor/signaling": {
			main: "lib/index.js"
		},
		"@phosphor/virtualdom": {
			main: "lib/index.js"
		},
		"@phosphor/widgets": {
			main: "lib/index.js"
		},
		"charto-leaflet": {
			main: "dist/index.js"
		},
		"charto-model": {
			main: "dist/index.js"
		},
		"classy-mst": {
			main: "dist/index.js"
		},
		"leaflet": {
			main: "dist/leaflet-src.js"
		},
		"mobx": {
			main: "lib/mobx.js"
		},
		"mobx-state-tree": {
			main: "dist/mobx-state-tree.js"
		},
		"object-assign": {
			main: "index.js"
		},
		"phosphor-float-area": {
			main: "dist/index.js"
		},
		"phosphor-leaflet": {
			main: "dist/index.js"
		},
		"react": {
			main: "index.js"
		},
		"react-dom": {
			main: "index.js"
		}
	}
});
